### ISSUE TITLE
移动端的开发

### ISSUE THREAD

**Issue by wenjiang** [huizhong/fantuan#1]
我是搞Android客户端开发的，可以帮忙搞一下客户端的开发，QQ;1220240057，到时在备注中说明一下就可以了

**Comment by huizhong** [comment]
当然可以了~ 这是个开放的项目。 但是你这样直接发issue真是太直接了。。。

**Comment by wenjiang** [comment]
是有点直接。。。如果觉得有影响的话，我可以删了，然后什么问题我们可以QQ或者其他方式交流。。。

**Comment by huizhong** [comment]
关注项目 然后比如对哪个issue有兴趣发pull request就好 要不然很有压力。。。

**Comment by wenjiang** [comment]
说得也是，哈哈，抱歉，之前我都是在issues这个版块和项目的主人聊天或者讨论问题的，一不小心就。。。
